### PR TITLE
fix bug #1

### PR DESCRIPTION
**Pull request by Faichyer**
Fixed by changing some shit

#1

### CODE REVIEW

**Review by Lelberto — APPROVED** [review]
Ok bro

**Comment by Faichyer** [comment]
Dont forget to comment and subscribe to the channel !

**Comment by Lelberto** [comment]
> Dont forget to comment and subscribe to the channel !

😠

**Comment by Faichyer** [comment]
Why deleting my poor branch dude ?

**Comment by Lelberto** [comment]
Because ur branch is merged bro... A merged branch can be deleted when merged (to avoid keeping too many branches).
This is clean dude, no problem :)

**Comment by Faichyer** [comment]
I thought this branch was like a minecart. If commits are villagers and the branch a minecart, therefore you shouldn't destroy it in a lava block right ?

**Comment by Lelberto** [comment]
Alt Text

**Comment by Faichyer** [comment]
Dear Jeremy Surieux, 
Let me explain myself about this tragedious removal of my beloved branch. 
If you remember well, our friend RhesusFC did a villagers farm on Minecraft, and he needed a minecart in order to transfer the villagers from their own village to ours. So if the commits I do are the villagers and ma branch is the minecart, the transfer wouldn't work if you destroy the minecart, do you get it now MISTER SURIEUX ??

**Comment by Lelberto** [comment]
Ok so, if a villager is a commit and a branch a minecart, you can only push a single commit per branch ? Your example sucks.

**Comment by Faichyer** [comment]
Wait you got a point here, let me find a counter example

**Comment by Lelberto** [comment]
No please, no........

**Comment by Faichyer** [comment]
It's basically like MK4 conveyors on Satistactory, you have multiple commits on one conveyor but if you break it, you can't supply your whole system, can you ?

**Comment by Lelberto** [comment]
You forgot the "merge" part. When a MK4 conveyor has multiple commits, it can be merged with a conveyor merger (or splitter). After that, the conveyor can be safely deleted.

**Comment by Faichyer** [comment]
Markdown Monster icon

**Pull request merged**
